package as.minecraft.util;

import org.spongepowered.api.item.ItemType;
import org.spongepowered.api.item.ItemTypes;

public class ItemTypeEnumerate
{
	public static ItemType getItemTypeFromItemId(String itemId)
	{
		switch(itemId)
		{
		case "minecraft:air":
			return ItemTypes.AIR;
		case "minecraft:stone":
			return ItemTypes.STONE;
		case "minecraft:grass":
			return ItemTypes.GRASS;
		case "minecraft:dirt":
			return ItemTypes.DIRT;
		case "minecraft:cobblestone":
			return ItemTypes.COBBLESTONE;
		case "minecraft:planks":
			return ItemTypes.PLANKS;
		case "minecraft:sapling":
			return ItemTypes.SAPLING;
		case "minecraft:bedrock":
			return ItemTypes.BEDROCK;
		case "minecraft:sand":
			return ItemTypes.SAND;
		case "minecraft:gravel":
			return ItemTypes.GRAVEL;
		case "minecraft:gold_ore":
			return ItemTypes.GOLD_ORE;
		case "minecraft:iron_ore":
			return ItemTypes.IRON_ORE;
		case "minecraft:coal_ore":
			return ItemTypes.COAL_ORE;
		case "minecraft:log":
			return ItemTypes.LOG;
		case "minecraft:leaves":
			return ItemTypes.LEAVES;
		case "minecraft:sponge":
			return ItemTypes.SPONGE;
		case "minecraft:glass":
			return ItemTypes.GLASS;
		case "minecraft:lapis_ore":
			return ItemTypes.LAPIS_ORE;
		case "minecraft:lapis_block":
			return ItemTypes.LAPIS_BLOCK;
		case "minecraft:dispenser":
			return ItemTypes.DISPENSER;
		case "minecraft:sandstone":
			return ItemTypes.SANDSTONE;
		case "minecraft:noteblock":
			return ItemTypes.NOTEBLOCK;
		case "minecraft:golden_rail":
			return ItemTypes.GOLDEN_RAIL;
		case "minecraft:detector_rail":
			return ItemTypes.DETECTOR_RAIL;
		case "minecraft:sticky_piston":
			return ItemTypes.STICKY_PISTON;
		case "minecraft:web":
			return ItemTypes.WEB;
		case "minecraft:tallgrass":
			return ItemTypes.TALLGRASS;
		case "minecraft:deadbush":
			return ItemTypes.DEADBUSH;
		case "minecraft:piston":
			return ItemTypes.PISTON;
		case "minecraft:wool":
			return ItemTypes.WOOL;
		case "minecraft:yellow_flower":
			return ItemTypes.YELLOW_FLOWER;
		case "minecraft:red_flower":
			return ItemTypes.RED_FLOWER;
		case "minecraft:brown_mushroom":
			return ItemTypes.BROWN_MUSHROOM;
		case "minecraft:red_mushroom":
			return ItemTypes.RED_MUSHROOM;
		case "minecraft:gold_block":
			return ItemTypes.GOLD_BLOCK;
		case "minecraft:iron_block":
			return ItemTypes.IRON_BLOCK;
		case "minecraft:stone_slab":
			return ItemTypes.STONE_SLAB;
		case "minecraft:brick_block":
			return ItemTypes.BRICK_BLOCK;
		case "minecraft:tnt":
			return ItemTypes.TNT;
		case "minecraft:bookshelf":
			return ItemTypes.BOOKSHELF;
		case "minecraft:mossy_cobblestone":
			return ItemTypes.MOSSY_COBBLESTONE;
		case "minecraft:obsidian":
			return ItemTypes.OBSIDIAN;
		case "minecraft:torch":
			return ItemTypes.TORCH;
		case "minecraft:mob_spawner":
			return ItemTypes.MOB_SPAWNER;
		case "minecraft:oak_stairs":
			return ItemTypes.OAK_STAIRS;
		case "minecraft:chest":
			return ItemTypes.CHEST;
		case "minecraft:diamond_ore":
			return ItemTypes.DIAMOND_ORE;
		case "minecraft:diamond_block":
			return ItemTypes.DIAMOND_BLOCK;
		case "minecraft:crafting_table":
			return ItemTypes.CRAFTING_TABLE;
		case "minecraft:wheat":
			return ItemTypes.WHEAT;
		case "minecraft:farmland":
			return ItemTypes.FARMLAND;
		case "minecraft:furnace":
			return ItemTypes.FURNACE;
		case "minecraft:ladder":
			return ItemTypes.LADDER;
		case "minecraft:rail":
			return ItemTypes.RAIL;
		case "minecraft:stone_stairs":
			return ItemTypes.STONE_STAIRS;
		case "minecraft:lever":
			return ItemTypes.LEVER;
		case "minecraft:stone_pressure_plate":
			return ItemTypes.STONE_PRESSURE_PLATE;
		case "minecraft:wooden_pressure_plate":
			return ItemTypes.WOODEN_PRESSURE_PLATE;
		case "minecraft:redstone_ore":
			return ItemTypes.REDSTONE_ORE;
		case "minecraft:redstone_torch":
			return ItemTypes.REDSTONE_TORCH;
		case "minecraft:stone_button":
			return ItemTypes.STONE_BUTTON;
		case "minecraft:snow_layer":
			return ItemTypes.SNOW_LAYER;
		case "minecraft:ice":
			return ItemTypes.ICE;
		case "minecraft:snow":
			return ItemTypes.SNOW;
		case "minecraft:cactus":
			return ItemTypes.CACTUS;
		case "minecraft:clay":
			return ItemTypes.CLAY;
		case "minecraft:jukebox":
			return ItemTypes.JUKEBOX;
		case "minecraft:fence":
			return ItemTypes.FENCE;
		case "minecraft:pumpkin":
			return ItemTypes.PUMPKIN;
		case "minecraft:netherrack":
			return ItemTypes.NETHERRACK;
		case "minecraft:soul_sand":
			return ItemTypes.SOUL_SAND;
		case "minecraft:glowstone":
			return ItemTypes.GLOWSTONE;
		case "minecraft:lit_pumpkin":
			return ItemTypes.LIT_PUMPKIN;
		case "minecraft:stained_glass":
			return ItemTypes.STAINED_GLASS;
		case "minecraft:trapdoor":
			return ItemTypes.TRAPDOOR;
		case "minecraft:monster_egg":
			return ItemTypes.MONSTER_EGG;
		case "minecraft:stonebrick":
			return ItemTypes.STONEBRICK;
		case "minecraft:brown_mushroom_block":
			return ItemTypes.BROWN_MUSHROOM_BLOCK;
		case "minecraft:red_mushroom_block":
			return ItemTypes.RED_MUSHROOM_BLOCK;
		case "minecraft:iron_bars":
			return ItemTypes.IRON_BARS;
		case "minecraft:glass_pane":
			return ItemTypes.GLASS_PANE;
		case "minecraft:melon_block":
			return ItemTypes.MELON_BLOCK;
		case "minecraft:vine":
			return ItemTypes.VINE;
		case "minecraft:fence_gate":
			return ItemTypes.FENCE_GATE;
		case "minecraft:brick_stairs":
			return ItemTypes.BRICK_STAIRS;
		case "minecraft:stone_brick_stairs":
			return ItemTypes.STONE_BRICK_STAIRS;
		case "minecraft:mycelium":
			return ItemTypes.MYCELIUM;
		case "minecraft:waterlily":
			return ItemTypes.WATERLILY;
		case "minecraft:nether_brick":
			return ItemTypes.NETHER_BRICK;
		case "minecraft:nether_brick_fence":
			return ItemTypes.NETHER_BRICK_FENCE;
		case "minecraft:nether_brick_stairs":
			return ItemTypes.NETHER_BRICK_STAIRS;
		case "minecraft:enchanting_table":
			return ItemTypes.ENCHANTING_TABLE;
		case "minecraft:end_portal_frame":
			return ItemTypes.END_PORTAL_FRAME;
		case "minecraft:end_stone":
			return ItemTypes.END_STONE;
		case "minecraft:dragon_egg":
			return ItemTypes.DRAGON_EGG;
		case "minecraft:redstone_lamp":
			return ItemTypes.REDSTONE_LAMP;
		case "minecraft:wooden_slab":
			return ItemTypes.WOODEN_SLAB;
		case "minecraft:sandstone_stairs":
			return ItemTypes.SANDSTONE_STAIRS;
		case "minecraft:emerald_ore":
			return ItemTypes.EMERALD_ORE;
		case "minecraft:ender_chest":
			return ItemTypes.ENDER_CHEST;
		case "minecraft:tripwire_hook":
			return ItemTypes.TRIPWIRE_HOOK;
		case "minecraft:emerald_block":
			return ItemTypes.EMERALD_BLOCK;
		case "minecraft:spruce_stairs":
			return ItemTypes.SPRUCE_STAIRS;
		case "minecraft:birch_stairs":
			return ItemTypes.BIRCH_STAIRS;
		case "minecraft:jungle_stairs":
			return ItemTypes.JUNGLE_STAIRS;
		case "minecraft:command_block":
			return ItemTypes.COMMAND_BLOCK;
		case "minecraft:beacon":
			return ItemTypes.BEACON;
		case "minecraft:cobblestone_wall":
			return ItemTypes.COBBLESTONE_WALL;
		case "minecraft:wooden_button":
			return ItemTypes.WOODEN_BUTTON;
		case "minecraft:anvil":
			return ItemTypes.ANVIL;
		case "minecraft:trapped_chest":
			return ItemTypes.TRAPPED_CHEST;
		case "minecraft:light_weighted_pressure_plate":
			return ItemTypes.LIGHT_WEIGHTED_PRESSURE_PLATE;
		case "minecraft:heavy_weighted_pressure_plate":
			return ItemTypes.HEAVY_WEIGHTED_PRESSURE_PLATE;
		case "minecraft:daylight_detector":
			return ItemTypes.DAYLIGHT_DETECTOR;
		case "minecraft:redstone_block":
			return ItemTypes.REDSTONE_BLOCK;
		case "minecraft:quartz_ore":
			return ItemTypes.QUARTZ_ORE;
		case "minecraft:hopper":
			return ItemTypes.HOPPER;
		case "minecraft:quartz_block":
			return ItemTypes.QUARTZ_BLOCK;
		case "minecraft:quartz_stairs":
			return ItemTypes.QUARTZ_STAIRS;
		case "minecraft:activator_rail":
			return ItemTypes.ACTIVATOR_RAIL;
		case "minecraft:dropper":
			return ItemTypes.DROPPER;
		case "minecraft:stained_hardened_clay":
			return ItemTypes.STAINED_HARDENED_CLAY;
		case "minecraft:stained_glass_pane":
			return ItemTypes.STAINED_GLASS_PANE;
		case "minecraft:leaves2":
			return ItemTypes.LEAVES2;
		case "minecraft:log2":
			return ItemTypes.LOG2;
		case "minecraft:acacia_stairs":
			return ItemTypes.ACACIA_STAIRS;
		case "minecraft:dark_oak_stairs":
			return ItemTypes.DARK_OAK_STAIRS;
		case "minecraft:slime":
			return ItemTypes.SLIME;
		case "minecraft:barrier":
			return ItemTypes.BARRIER;
		case "minecraft:iron_trapdoor":
			return ItemTypes.IRON_TRAPDOOR;
		case "minecraft:prismarine":
			return ItemTypes.PRISMARINE;
		case "minecraft:sea_lantern":
			return ItemTypes.SEA_LANTERN;
		case "minecraft:hay_block":
			return ItemTypes.HAY_BLOCK;
		case "minecraft:carpet":
			return ItemTypes.CARPET;
		case "minecraft:hardened_clay":
			return ItemTypes.HARDENED_CLAY;
		case "minecraft:coal_block":
			return ItemTypes.COAL_BLOCK;
		case "minecraft:packed_ice":
			return ItemTypes.PACKED_ICE;
		case "minecraft:double_plant":
			return ItemTypes.DOUBLE_PLANT;
		case "minecraft:red_sandstone":
			return ItemTypes.RED_SANDSTONE;
		case "minecraft:red_sandstone_stairs":
			return ItemTypes.RED_SANDSTONE_STAIRS;
		case "minecraft:stone_slab2":
			return ItemTypes.STONE_SLAB2;
		case "minecraft:spruce_fence_gate":
			return ItemTypes.SPRUCE_FENCE_GATE;
		case "minecraft:birch_fence_gate":
			return ItemTypes.BIRCH_FENCE_GATE;
		case "minecraft:jungle_fence_gate":
			return ItemTypes.JUNGLE_FENCE_GATE;
		case "minecraft:dark_oak_fence_gate":
			return ItemTypes.DARK_OAK_FENCE_GATE;
		case "minecraft:acacia_fence_gate":
			return ItemTypes.ACACIA_FENCE_GATE;
		case "minecraft:spruce_fence":
			return ItemTypes.SPRUCE_FENCE;
		case "minecraft:birch_fence":
			return ItemTypes.BIRCH_FENCE;
		case "minecraft:jungle_fence":
			return ItemTypes.JUNGLE_FENCE;
		case "minecraft:dark_oak_fence":
			return ItemTypes.DARK_OAK_FENCE;
		case "minecraft:acacia_fence":
			return ItemTypes.ACACIA_FENCE;
		case "minecraft:end_rod":
			return ItemTypes.END_ROD;
		case "minecraft:chorus_plant":
			return ItemTypes.CHORUS_PLANT;
		case "minecraft:chorus_flower":
			return ItemTypes.CHORUS_FLOWER;
		case "minecraft:purpur_block":
			return ItemTypes.PURPUR_BLOCK;
		case "minecraft:purpur_pillar":
			return ItemTypes.PURPUR_PILLAR;
		case "minecraft:purpur_stairs":
			return ItemTypes.PURPUR_STAIRS;
		case "minecraft:purpur_slab":
			return ItemTypes.PURPUR_SLAB;
		case "minecraft:end_bricks":
			return ItemTypes.END_BRICKS;
		case "minecraft:grass_path":
			return ItemTypes.GRASS_PATH;
		case "minecraft:repeating_command_block":
			return ItemTypes.REPEATING_COMMAND_BLOCK;
		case "minecraft:chain_command_block":
			return ItemTypes.CHAIN_COMMAND_BLOCK;
		case "minecraft:magma":
			return ItemTypes.MAGMA;
		case "minecraft:nether_wart_block":
			return ItemTypes.NETHER_WART_BLOCK;
		case "minecraft:red_nether_brick":
			return ItemTypes.RED_NETHER_BRICK;
		case "minecraft:bone_block":
			return ItemTypes.BONE_BLOCK;
		case "minecraft:structure_void":
			return ItemTypes.STRUCTURE_VOID;
		case "minecraft:observer":
			return ItemTypes.OBSERVER;
		case "minecraft:white_shulker_box":
			return ItemTypes.WHITE_SHULKER_BOX;
		case "minecraft:orange_shulker_box":
			return ItemTypes.ORANGE_SHULKER_BOX;
		case "minecraft:magenta_shulker_box":
			return ItemTypes.MAGENTA_SHULKER_BOX;
		case "minecraft:light_blue_shulker_box":
			return ItemTypes.LIGHT_BLUE_SHULKER_BOX;
		case "minecraft:yellow_shulker_box":
			return ItemTypes.YELLOW_SHULKER_BOX;
		case "minecraft:lime_shulker_box":
			return ItemTypes.LIME_SHULKER_BOX;
		case "minecraft:pink_shulker_box":
			return ItemTypes.PINK_SHULKER_BOX;
		case "minecraft:gray_shulker_box":
			return ItemTypes.GRAY_SHULKER_BOX;
		case "minecraft:silver_shulker_box":
			return ItemTypes.SILVER_SHULKER_BOX;
		case "minecraft:cyan_shulker_box":
			return ItemTypes.CYAN_SHULKER_BOX;
		case "minecraft:purple_shulker_box":
			return ItemTypes.PURPLE_SHULKER_BOX;
		case "minecraft:blue_shulker_box":
			return ItemTypes.BLUE_SHULKER_BOX;
		case "minecraft:brown_shulker_box":
			return ItemTypes.BROWN_SHULKER_BOX;
		case "minecraft:green_shulker_box":
			return ItemTypes.GREEN_SHULKER_BOX;
		case "minecraft:red_shulker_box":
			return ItemTypes.RED_SHULKER_BOX;
		case "minecraft:black_shulker_box":
			return ItemTypes.BLACK_SHULKER_BOX;
		/*case "minecraft:white_glazed_terracotta":
			return ItemTypes.WHITE_GLAZED_TERRACOTTA;
		case "minecraft:orange_glazed_terracotta":
			return ItemTypes.ORANGE_GLAZED_TERRACOTTA;
		case "minecraft:magenta_glazed_terracotta":
			return ItemTypes.MAGENTA_GLAZED_TERRACOTTA;
		case "minecraft:light_blue_glazed_terracotta":
			return ItemTypes.LIGHT_BLUE_GLAZED_TERRACOTTA;
		case "minecraft:yellow_glazed_terracotta":
			return ItemTypes.YELLOW_GLAZED_TERRACOTTA;
		case "minecraft:lime_glazed_terracotta":
			return ItemTypes.LIME_GLAZED_TERRACOTTA;
		case "minecraft:pink_glazed_terracotta":
			return ItemTypes.PINK_GLAZED_TERRACOTTA;
		case "minecraft:gray_glazed_terracotta":
			return ItemTypes.GRAY_GLAZED_TERRACOTTA;
		case "minecraft:silver_glazed_terracotta":
			return ItemTypes.SILVER_GLAZED_TERRACOTTA;
		case "minecraft:cyan_glazed_terracotta":
			return ItemTypes.CYAN_GLAZED_TERRACOTTA;
		case "minecraft:purple_glazed_terracotta":
			return ItemTypes.PURPLE_GLAZED_TERRACOTTA;
		case "minecraft:blue_glazed_terracotta":
			return ItemTypes.BLUE_GLAZED_TERRACOTTA;
		case "minecraft:brown_glazed_terracotta":
			return ItemTypes.BROWN_GLAZED_TERRACOTTA;
		case "minecraft:green_glazed_terracotta":
			return ItemTypes.GREEN_GLAZED_TERRACOTTA;
		case "minecraft:red_glazed_terracotta":
			return ItemTypes.RED_GLAZED_TERRACOTTA;
		case "minecraft:black_glazed_terracotta":
			return ItemTypes.BLACK_GLAZED_TERRACOTTA;
		case "minecraft:concrete":
			return ItemTypes.CONCRETE;
		case "minecraft:concrete_powder":
			return ItemTypes.CONCRETE_POWDER;*/
		case "minecraft:structure_block":
			return ItemTypes.STRUCTURE_BLOCK;
		case "minecraft:iron_shovel":
			return ItemTypes.IRON_SHOVEL;
		case "minecraft:iron_pickaxe":
			return ItemTypes.IRON_PICKAXE;
		case "minecraft:iron_axe":
			return ItemTypes.IRON_AXE;
		case "minecraft:flint_and_steel":
			return ItemTypes.FLINT_AND_STEEL;
		case "minecraft:apple":
			return ItemTypes.APPLE;
		case "minecraft:bow":
			return ItemTypes.BOW;
		case "minecraft:arrow":
			return ItemTypes.ARROW;
		case "minecraft:coal":
			return ItemTypes.COAL;
		case "minecraft:diamond":
			return ItemTypes.DIAMOND;
		case "minecraft:iron_ingot":
			return ItemTypes.IRON_INGOT;
		case "minecraft:gold_ingot":
			return ItemTypes.GOLD_INGOT;
		case "minecraft:iron_sword":
			return ItemTypes.IRON_SWORD;
		case "minecraft:wooden_sword":
			return ItemTypes.WOODEN_SWORD;
		case "minecraft:wooden_shovel":
			return ItemTypes.WOODEN_SHOVEL;
		case "minecraft:wooden_pickaxe":
			return ItemTypes.WOODEN_PICKAXE;
		case "minecraft:wooden_axe":
			return ItemTypes.WOODEN_AXE;
		case "minecraft:stone_sword":
			return ItemTypes.STONE_SWORD;
		case "minecraft:stone_shovel":
			return ItemTypes.STONE_SHOVEL;
		case "minecraft:stone_pickaxe":
			return ItemTypes.STONE_PICKAXE;
		case "minecraft:stone_axe":
			return ItemTypes.STONE_AXE;
		case "minecraft:diamond_sword":
			return ItemTypes.DIAMOND_SWORD;
		case "minecraft:diamond_shovel":
			return ItemTypes.DIAMOND_SHOVEL;
		case "minecraft:diamond_pickaxe":
			return ItemTypes.DIAMOND_PICKAXE;
		case "minecraft:diamond_axe":
			return ItemTypes.DIAMOND_AXE;
		case "minecraft:stick":
			return ItemTypes.STICK;
		case "minecraft:bowl":
			return ItemTypes.BOWL;
		case "minecraft:mushroom_stew":
			return ItemTypes.MUSHROOM_STEW;
		case "minecraft:golden_sword":
			return ItemTypes.GOLDEN_SWORD;
		case "minecraft:golden_shovel":
			return ItemTypes.GOLDEN_SHOVEL;
		case "minecraft:golden_pickaxe":
			return ItemTypes.GOLDEN_PICKAXE;
		case "minecraft:golden_axe":
			return ItemTypes.GOLDEN_AXE;
		case "minecraft:string":
			return ItemTypes.STRING;
		case "minecraft:feather":
			return ItemTypes.FEATHER;
		case "minecraft:gunpowder":
			return ItemTypes.GUNPOWDER;
		case "minecraft:wooden_hoe":
			return ItemTypes.WOODEN_HOE;
		case "minecraft:stone_hoe":
			return ItemTypes.STONE_HOE;
		case "minecraft:iron_hoe":
			return ItemTypes.IRON_HOE;
		case "minecraft:diamond_hoe":
			return ItemTypes.DIAMOND_HOE;
		case "minecraft:golden_hoe":
			return ItemTypes.GOLDEN_HOE;
		case "minecraft:wheat_seeds":
			return ItemTypes.WHEAT_SEEDS;
		case "minecraft:bread":
			return ItemTypes.BREAD;
		case "minecraft:leather_helmet":
			return ItemTypes.LEATHER_HELMET;
		case "minecraft:leather_chestplate":
			return ItemTypes.LEATHER_CHESTPLATE;
		case "minecraft:leather_leggings":
			return ItemTypes.LEATHER_LEGGINGS;
		case "minecraft:leather_boots":
			return ItemTypes.LEATHER_BOOTS;
		case "minecraft:chainmail_helmet":
			return ItemTypes.CHAINMAIL_HELMET;
		case "minecraft:chainmail_chestplate":
			return ItemTypes.CHAINMAIL_CHESTPLATE;
		case "minecraft:chainmail_leggings":
			return ItemTypes.CHAINMAIL_LEGGINGS;
		case "minecraft:chainmail_boots":
			return ItemTypes.CHAINMAIL_BOOTS;
		case "minecraft:iron_helmet":
			return ItemTypes.IRON_HELMET;
		case "minecraft:iron_chestplate":
			return ItemTypes.IRON_CHESTPLATE;
		case "minecraft:iron_leggings":
			return ItemTypes.IRON_LEGGINGS;
		case "minecraft:iron_boots":
			return ItemTypes.IRON_BOOTS;
		case "minecraft:diamond_helmet":
			return ItemTypes.DIAMOND_HELMET;
		case "minecraft:diamond_chestplate":
			return ItemTypes.DIAMOND_CHESTPLATE;
		case "minecraft:diamond_leggings":
			return ItemTypes.DIAMOND_LEGGINGS;
		case "minecraft:diamond_boots":
			return ItemTypes.DIAMOND_BOOTS;
		case "minecraft:golden_helmet":
			return ItemTypes.GOLDEN_HELMET;
		case "minecraft:golden_chestplate":
			return ItemTypes.GOLDEN_CHESTPLATE;
		case "minecraft:golden_leggings":
			return ItemTypes.GOLDEN_LEGGINGS;
		case "minecraft:golden_boots":
			return ItemTypes.GOLDEN_BOOTS;
		case "minecraft:flint":
			return ItemTypes.FLINT;
		case "minecraft:porkchop":
			return ItemTypes.PORKCHOP;
		case "minecraft:cooked_porkchop":
			return ItemTypes.COOKED_PORKCHOP;
		case "minecraft:painting":
			return ItemTypes.PAINTING;
		case "minecraft:golden_apple":
			return ItemTypes.GOLDEN_APPLE;
		case "minecraft:sign":
			return ItemTypes.SIGN;
		case "minecraft:wooden_door":
			return ItemTypes.WOODEN_DOOR;
		case "minecraft:bucket":
			return ItemTypes.BUCKET;
		case "minecraft:water_bucket":
			return ItemTypes.WATER_BUCKET;
		case "minecraft:lava_bucket":
			return ItemTypes.LAVA_BUCKET;
		case "minecraft:minecart":
			return ItemTypes.MINECART;
		case "minecraft:saddle":
			return ItemTypes.SADDLE;
		case "minecraft:iron_door":
			return ItemTypes.IRON_DOOR;
		case "minecraft:redstone":
			return ItemTypes.REDSTONE;
		case "minecraft:snowball":
			return ItemTypes.SNOWBALL;
		case "minecraft:boat":
			return ItemTypes.BOAT;
		case "minecraft:leather":
			return ItemTypes.LEATHER;
		case "minecraft:milk_bucket":
			return ItemTypes.MILK_BUCKET;
		case "minecraft:brick":
			return ItemTypes.BRICK;
		case "minecraft:clay_ball":
			return ItemTypes.CLAY_BALL;
		case "minecraft:reeds":
			return ItemTypes.REEDS;
		case "minecraft:paper":
			return ItemTypes.PAPER;
		case "minecraft:book":
			return ItemTypes.BOOK;
		case "minecraft:slime_ball":
			return ItemTypes.SLIME_BALL;
		case "minecraft:chest_minecart":
			return ItemTypes.CHEST_MINECART;
		case "minecraft:furnace_minecart":
			return ItemTypes.FURNACE_MINECART;
		case "minecraft:egg":
			return ItemTypes.EGG;
		case "minecraft:compass":
			return ItemTypes.COMPASS;
		case "minecraft:fishing_rod":
			return ItemTypes.FISHING_ROD;
		case "minecraft:clock":
			return ItemTypes.CLOCK;
		case "minecraft:glowstone_dust":
			return ItemTypes.GLOWSTONE_DUST;
		case "minecraft:fish":
			return ItemTypes.FISH;
		case "minecraft:cooked_fish":
			return ItemTypes.COOKED_FISH;
		case "minecraft:dye":
			return ItemTypes.DYE;
		case "minecraft:bone":
			return ItemTypes.BONE;
		case "minecraft:sugar":
			return ItemTypes.SUGAR;
		case "minecraft:cake":
			return ItemTypes.CAKE;
		case "minecraft:bed":
			return ItemTypes.BED;
		case "minecraft:repeater":
			return ItemTypes.REPEATER;
		case "minecraft:cookie":
			return ItemTypes.COOKIE;
		case "minecraft:filled_map":
			return ItemTypes.FILLED_MAP;
		case "minecraft:shears":
			return ItemTypes.SHEARS;
		case "minecraft:melon":
			return ItemTypes.MELON;
		case "minecraft:pumpkin_seeds":
			return ItemTypes.PUMPKIN_SEEDS;
		case "minecraft:melon_seeds":
			return ItemTypes.MELON_SEEDS;
		case "minecraft:beef":
			return ItemTypes.BEEF;
		case "minecraft:cooked_beef":
			return ItemTypes.COOKED_BEEF;
		case "minecraft:chicken":
			return ItemTypes.CHICKEN;
		case "minecraft:cooked_chicken":
			return ItemTypes.COOKED_CHICKEN;
		case "minecraft:rotten_flesh":
			return ItemTypes.ROTTEN_FLESH;
		case "minecraft:ender_pearl":
			return ItemTypes.ENDER_PEARL;
		case "minecraft:blaze_rod":
			return ItemTypes.BLAZE_ROD;
		case "minecraft:ghast_tear":
			return ItemTypes.GHAST_TEAR;
		case "minecraft:gold_nugget":
			return ItemTypes.GOLD_NUGGET;
		case "minecraft:nether_wart":
			return ItemTypes.NETHER_WART;
		case "minecraft:potion":
			return ItemTypes.POTION;
		case "minecraft:glass_bottle":
			return ItemTypes.GLASS_BOTTLE;
		case "minecraft:spider_eye":
			return ItemTypes.SPIDER_EYE;
		case "minecraft:fermented_spider_eye":
			return ItemTypes.FERMENTED_SPIDER_EYE;
		case "minecraft:blaze_powder":
			return ItemTypes.BLAZE_POWDER;
		case "minecraft:magma_cream":
			return ItemTypes.MAGMA_CREAM;
		case "minecraft:brewing_stand":
			return ItemTypes.BREWING_STAND;
		case "minecraft:cauldron":
			return ItemTypes.CAULDRON;
		case "minecraft:ender_eye":
			return ItemTypes.ENDER_EYE;
		case "minecraft:speckled_melon":
			return ItemTypes.SPECKLED_MELON;
		case "minecraft:spawn_egg":
			return ItemTypes.SPAWN_EGG;
		case "minecraft:experience_bottle":
			return ItemTypes.EXPERIENCE_BOTTLE;
		case "minecraft:fire_charge":
			return ItemTypes.FIRE_CHARGE;
		case "minecraft:writable_book":
			return ItemTypes.WRITABLE_BOOK;
		case "minecraft:written_book":
			return ItemTypes.WRITTEN_BOOK;
		case "minecraft:emerald":
			return ItemTypes.EMERALD;
		case "minecraft:item_frame":
			return ItemTypes.ITEM_FRAME;
		case "minecraft:flower_pot":
			return ItemTypes.FLOWER_POT;
		case "minecraft:carrot":
			return ItemTypes.CARROT;
		case "minecraft:potato":
			return ItemTypes.POTATO;
		case "minecraft:baked_potato":
			return ItemTypes.BAKED_POTATO;
		case "minecraft:poisonous_potato":
			return ItemTypes.POISONOUS_POTATO;
		case "minecraft:map":
			return ItemTypes.MAP;
		case "minecraft:golden_carrot":
			return ItemTypes.GOLDEN_CARROT;
		case "minecraft:skull":
			return ItemTypes.SKULL;
		case "minecraft:carrot_on_a_stick":
			return ItemTypes.CARROT_ON_A_STICK;
		case "minecraft:nether_star":
			return ItemTypes.NETHER_STAR;
		case "minecraft:pumpkin_pie":
			return ItemTypes.PUMPKIN_PIE;
		case "minecraft:fireworks":
			return ItemTypes.FIREWORKS;
		case "minecraft:firework_charge":
			return ItemTypes.FIREWORK_CHARGE;
		case "minecraft:enchanted_book":
			return ItemTypes.ENCHANTED_BOOK;
		case "minecraft:comparator":
			return ItemTypes.COMPARATOR;
		case "minecraft:netherbrick":
			return ItemTypes.NETHERBRICK;
		case "minecraft:quartz":
			return ItemTypes.QUARTZ;
		case "minecraft:tnt_minecart":
			return ItemTypes.TNT_MINECART;
		case "minecraft:hopper_minecart":
			return ItemTypes.HOPPER_MINECART;
		case "minecraft:prismarine_shard":
			return ItemTypes.PRISMARINE_SHARD;
		case "minecraft:prismarine_crystals":
			return ItemTypes.PRISMARINE_CRYSTALS;
		case "minecraft:rabbit":
			return ItemTypes.RABBIT;
		case "minecraft:cooked_rabbit":
			return ItemTypes.COOKED_RABBIT;
		case "minecraft:rabbit_stew":
			return ItemTypes.RABBIT_STEW;
		case "minecraft:rabbit_foot":
			return ItemTypes.RABBIT_FOOT;
		case "minecraft:rabbit_hide":
			return ItemTypes.RABBIT_HIDE;
		case "minecraft:armor_stand":
			return ItemTypes.ARMOR_STAND;
		case "minecraft:iron_horse_armor":
			return ItemTypes.IRON_HORSE_ARMOR;
		case "minecraft:golden_horse_armor":
			return ItemTypes.GOLDEN_HORSE_ARMOR;
		case "minecraft:diamond_horse_armor":
			return ItemTypes.DIAMOND_HORSE_ARMOR;
		case "minecraft:lead":
			return ItemTypes.LEAD;
		case "minecraft:name_tag":
			return ItemTypes.NAME_TAG;
		case "minecraft:command_block_minecart":
			return ItemTypes.COMMAND_BLOCK_MINECART;
		case "minecraft:mutton":
			return ItemTypes.MUTTON;
		case "minecraft:cooked_mutton":
			return ItemTypes.COOKED_MUTTON;
		case "minecraft:banner":
			return ItemTypes.BANNER;
		case "minecraft:end_crystal":
			return ItemTypes.END_CRYSTAL;
		case "minecraft:spruce_door":
			return ItemTypes.SPRUCE_DOOR;
		case "minecraft:birch_door":
			return ItemTypes.BIRCH_DOOR;
		case "minecraft:jungle_door":
			return ItemTypes.JUNGLE_DOOR;
		case "minecraft:acacia_door":
			return ItemTypes.ACACIA_DOOR;
		case "minecraft:dark_oak_door":
			return ItemTypes.DARK_OAK_DOOR;
		case "minecraft:chorus_fruit":
			return ItemTypes.CHORUS_FRUIT;
		case "minecraft:chorus_fruit_popped":
			return ItemTypes.CHORUS_FRUIT_POPPED;
		case "minecraft:beetroot":
			return ItemTypes.BEETROOT;
		case "minecraft:beetroot_seeds":
			return ItemTypes.BEETROOT_SEEDS;
		case "minecraft:beetroot_soup":
			return ItemTypes.BEETROOT_SOUP;
		case "minecraft:dragon_breath":
			return ItemTypes.DRAGON_BREATH;
		case "minecraft:splash_potion":
			return ItemTypes.SPLASH_POTION;
		case "minecraft:spectral_arrow":
			return ItemTypes.SPECTRAL_ARROW;
		case "minecraft:tipped_arrow":
			return ItemTypes.TIPPED_ARROW;
		case "minecraft:lingering_potion":
			return ItemTypes.LINGERING_POTION;
		case "minecraft:shield":
			return ItemTypes.SHIELD;
		case "minecraft:elytra":
			return ItemTypes.ELYTRA;
		case "minecraft:spruce_boat":
			return ItemTypes.SPRUCE_BOAT;
		case "minecraft:birch_boat":
			return ItemTypes.BIRCH_BOAT;
		case "minecraft:jungle_boat":
			return ItemTypes.JUNGLE_BOAT;
		case "minecraft:acacia_boat":
			return ItemTypes.ACACIA_BOAT;
		case "minecraft:dark_oak_boat":
			return ItemTypes.DARK_OAK_BOAT;
		case "minecraft:totem_of_undying":
			return ItemTypes.TOTEM_OF_UNDYING;
		case "minecraft:shulker_shell":
			return ItemTypes.SHULKER_SHELL;
		case "minecraft:iron_nugget":
			return ItemTypes.IRON_NUGGET;
		case "minecraft:record_13":
			return ItemTypes.RECORD_13;
		case "minecraft:record_cat":
			return ItemTypes.RECORD_CAT;
		case "minecraft:record_blocks":
			return ItemTypes.RECORD_BLOCKS;
		case "minecraft:record_chirp":
			return ItemTypes.RECORD_CHIRP;
		case "minecraft:record_far":
			return ItemTypes.RECORD_FAR;
		case "minecraft:record_mall":
			return ItemTypes.RECORD_MALL;
		case "minecraft:record_mellohi":
			return ItemTypes.RECORD_MELLOHI;
		case "minecraft:record_stal":
			return ItemTypes.RECORD_STAL;
		case "minecraft:record_strad":
			return ItemTypes.RECORD_STRAD;
		case "minecraft:record_ward":
			return ItemTypes.RECORD_WARD;
		case "minecraft:record_11":
			return ItemTypes.RECORD_11;
		case "minecraft:record_wait":
			return ItemTypes.RECORD_WAIT;
		default: 
			return null;
		}
	}
}